
    create table packages (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table products (
        price float(53) not null,
        weight float(53) not null,
        id bigint generated by default as identity,
        package_id bigint not null,
        primary key (id)
    );

    alter table if exists products 
       add constraint FKhhhyxupe3r7vjtx8qoj1pagyg 
       foreign key (package_id) 
       references packages;
